name: Build and Release CRX

on:
  push:
    tags:
      - 'v*' # 当你推送以 v 开头的 tag（如 v1.0.0）时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build extension zip
        run: |
          zip -r bilibili-speed-master.zip manifest.json src icons

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            bilibili-speed-master.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
